### ISSUE TITLE
Criar container de property

### ISSUE THREAD

**Issue by guerraem** [EsfingeFramework/metadata#35]
Tem que buscar anotação no atributo, método getter e setter.

Essa anotação deve permitir a configuração de onde você busca a anotação. Com valores ALL, ATTRIBUTE_ONLY, ATTRIBUTE_GETTER, ATTRIBUTE_SETTER, GETTER_ONLY, SETTER_ONLY, GETTER_SETTER (criar um Enum chamado AnnotationPropertyLocation).

Quando fizer esse, criar uma anotação de processor similar a de Method e Fields.

**Comment by guerraem** [comment]
Deve ter um atributo que recebe um valor de um Enum que tem as opções acima!

**Comment by marconardes** [comment]
Verificar a classe PropiertiesInternData
