### ISSUE TITLE
Refactoring de processors

### ISSUE THREAD

**Issue by guerraem** [EsfingeFramework/metadata#46]
- Renomear READER_ADDS_PROCESSOR para READER_ADDS_METADATA
- Renomear @Processors para @CustomReader
- Melhorar nomes dos exemplos - por exemplo, ProcessAnnotation.class para CustomReaderAnnotation.class
- Renomear value para configAnnotation

Separar as seguintes annotations:
- @CustomReader vai processar os readers do próprio elemento - pode estar na classe e pode estar em uma collection - pode ter os 3 tipos
- @ProcessorPerMethod (substitui @MethodProcessors) - pega o primeiro processor encontrado por method - somente em um Map que o primeiro genérico seja Method (só é válido READER_IS_PROCESSOR e READER_RETURNS_PROCESSOR)
- @ProcessorPerField (substitui @FieldProcessors)

Atualizar documentação no final

**Comment by marconardes** [comment]
Finalizei os processors, agora.
